using AK.ToDo.Contracts.DataAccess.Entities;
using AK.ToDo.Contracts.DataAccess.Repositories;
// -----------------------------------------------------------------------
// <autogenerated>
//  This code was generated by Aashish Koirala's Text Templating Library.
//  Do not make changes to this code as they will be lost.
// </autogenerated>
// -----------------------------------------------------------------------

using System;
using System.ComponentModel.Composition;
using AK.Commons.DataAccess;
namespace AK.ToDo.DataAccess.Repositories
{
    [Export(typeof(IAppUserRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class AppUserRepository : RepositoryBase<AppUser, Guid>, IAppUserRepository { }
    [Export(typeof(IToDoCategoryRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class ToDoCategoryRepository : RepositoryBase<ToDoCategory, Guid>, IToDoCategoryRepository { }
    [Export(typeof(IToDoItemRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class ToDoItemRepository : RepositoryBase<ToDoItem, Guid>, IToDoItemRepository { }
    [Export(typeof(IItemCategoryRepository))] [PartCreationPolicy(CreationPolicy.Shared)] public partial class ItemCategoryRepository : RepositoryBase<ItemCategory, Guid>, IItemCategoryRepository { }
}
