// -----------------------------------------------------------------------
// <autogenerated>
//  This code was generated by Aashish Koirala's Text Templating Library.
//  Do not make changes to this code as they will be lost.
// </autogenerated>
// -----------------------------------------------------------------------

using System;
namespace AK.ToDo.Contracts.DataAccess.Entities
{
    public partial class AppUser
    {
        public virtual Guid Id { get; set; }
        public virtual string UserName { get; set; }
        public virtual System.Collections.Generic.IList<ToDoCategory> CategoryList { get; set; }
        public virtual System.Collections.Generic.IList<ToDoItem> ToDoList { get; set; }
    }

    public partial class ToDoCategory
    {
        public virtual Guid Id { get; set; }
        public virtual string Name { get; set; }
        public virtual Guid? ParentId { get; set; }
        public virtual Guid AppUserId { get; set; }
    }

    public partial class ToDoItem
    {
        public virtual Guid Id { get; set; }
        public virtual string Description { get; set; }
        public virtual string State { get; set; }
        public virtual DateTime? ScheduledStartDate { get; set; }
        public virtual DateTime ScheduledEndDate { get; set; }
        public virtual DateTime? ActualStartDate { get; set; }
        public virtual DateTime? ActualEndDate { get; set; }
        public virtual Guid AppUserId { get; set; }
    }

    public partial class ItemCategory
    {
        public virtual Guid Id { get; set; }
        public virtual Guid ItemId { get; set; }
        public virtual Guid CategoryId { get; set; }
    }

}
