using AK.ToDo.Contracts.DataAccess.Entities;
// -----------------------------------------------------------------------
// <autogenerated>
//  This code was generated by Aashish Koirala's Text Templating Library.
//  Do not make changes to this code as they will be lost.
// </autogenerated>
// -----------------------------------------------------------------------

using System;
using AK.Commons.DataAccess;
namespace AK.ToDo.Contracts.DataAccess.Repositories
{
    public partial interface IAppUserRepository : IRepository<AppUser, Guid> { }
    public partial interface IToDoCategoryRepository : IRepository<ToDoCategory, Guid> { }
    public partial interface IToDoItemRepository : IRepository<ToDoItem, Guid> { }
    public partial interface IItemCategoryRepository : IRepository<ItemCategory, Guid> { }
}
